import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const overusedgrotesk = localFont({
  src: [
    {
      path: "../../public/OverusedGrotesk-VF.woff2",
    },
  ],
  display: "block",
  variable: "--font-overusedgrotesk",
  weight: "200 800",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${overusedgrotesk.variable}`}>
      <body className="font-overusedgrotesk antialiased bg-[#F5EDED]">
        {children}
      </body>
    </html>
  );
}
